version: "3.9"

services:
  web:
    build: .
    command: uvicorn --factory src.app:create_app --host 0.0.0.0 --port 8000 --workers 6
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
      - ./images:/app/images
    ports:
      - target: 8000
        published: 8000
        mode: host
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      interval: 5s
      timeout: 5s
      start_period: 20s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    networks:
      - backend

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/data"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - target: 5432
        published: 15432
        mode: host
    command: postgres -c 'max_connections=500'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d service"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend: